language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
# Weould like to be python 3.2 compliant but not there yet.
matrix:
  allow_failures:
    - python: 3.2
# command to install dependencies
install:
  - "python setup.py install"
  - "pip install -r test_requirements.txt"
  - "pip install flake8"
script:
    # Running PEP8 compliance
  - "flake8 --ignore=E501 jtime"
    # Running the unit tests
  - "nosetests --with-coverage --cover-package jtime"
    # Testing the distribution creation
  - "python setup.py sdist"
    # Testing the distribution installation
  - "find ./dist -iname '*.tar.gz' -print0 | xargs -0 pip install"
after_script:
  # Report coverage results to coveralls.io
  - pip install coveralls
  - coveralls
